### ISSUE TITLE
conflict with org-table-of-content

### ISSUE THREAD

**Issue by sunznx** [ardumont/org2jekyll#29]
if I set  "org-export-with-toc t"  
then the html file ...
    
![screenshot from 2015-12-28 10-21-32](https://cloud.githubusercontent.com/assets/8629792/12013205/dff4f784-ad4c-11e5-86f6-ab6217c42001.png)

**Comment by sunznx** [comment]
....

**Comment by ardumont** [comment]
Right, i forgot about it.
I have not found the time yet.

**Comment by sunznx** [comment]
I use toc-org  and it works fine! Thank you

**Comment by ardumont** [comment]
Hello,

You mean that:
- you set the org option 'toc:nil' and did not let org do the TOC
generation at publish time
- and you use toc-org to generate inside the org file the TOC

Am I right?

I think the trouble is that I, wrongly, expected the file being complete
before manipulation (what org2jekyll does).

But as the TOC seems generated after the publication so after org2jekyll
manipulation so the yaml ends up being after the TOC... As you showed. Thus
I imagined badly rendered in live.

It's still a bug on org2jekyll though.

Cheers,

**Comment by ardumont** [comment]
Hello,

> You mean that: 
> - you set the org option 'toc:nil' and did not let org do the TOC generation at publish time 
> - and you use toc-org to generate inside the org file the TOC 

Can you please tell me if my hypothesis of what i understand you did is right?

Cheers,

**Comment by sunznx** [comment]
sorry, my english is bad -.-
you are right. I set "toc:nil", then I use toc-org to navigate the header in org file and export to html, like this
* Table of Contents                                              :TOC@3@org:
:PROPERTIES:
:CUSTOM_ID: org-toc
:END:
 - [[xxx][xxx]]
   - [[xxx][xxx]]
- [[xxx][xxx]]

**Comment by ardumont** [comment]
> sorry, my english is bad -.- 

Not that much, don't worry.
There are always room for misinterpretation, you know :D 

> Those day are Chinese New Year, I didn't notice.

Happy new year!

> you are right. I set "toc:nil", then I use toc-org to navigate the header in org file and export to html, like this ...

Thanks!

> It's still a bug on org2jekyll though.

So i stand by this sentence. It's still a bug on org2jekyll's side and your workaround is to use toc-org.

Thanks for your feedback.

Cheers,

**Comment by yefeiyu** [comment]
when we solution this bug? :-)

**Comment by yefeiyu** [comment]
When shall  we soluted this bug? :-)
