### ISSUE TITLE
Incompatibility problem with deferred > 0.3.1

### ISSUE THREAD

**Issue by lujianmei** [ardumont/org2jekyll#43]
Great work!
I installed the newest deferred, version was 20161228.1930, then the org2jekyll would not be started, got an error message: 
Symbol's function definition is void: cl-struct-define.
After i changed to deferred-0.3.1, then it is ok now.
Suggest to solve this issue. Or marked the dependency version on your read me.
Thanks.

**Comment by ardumont** [comment]
Hello,

Thanks for your report.

> Suggest to solve this issue.

Mmm, it is marked in the source code https://github.com/ardumont/org2jekyll/blob/master/org2jekyll.el#L8 which is there for package purposes. I mean, it should be respected by the "package manager".

Anyway, the thing is, this unfortunately depends on a lot of variables.
Which package repository you use for example. It seems to be melpa here.
But also, which emacs version you use. Here i'd guess emacs24 or before that.
(`cl-struct-define` is defined as an internal symbol on emacs25 and not on emacs24)

> Or marked the dependency version on your read me.

This seems quite reasonable and to refer to this issue for more details.
Thanks again.

Cheers,

**Comment by lujianmei** [comment]
Oh yeah, i am using emacs25, i just found lots of package have cl-struct-define issue.  

**Comment by ardumont** [comment]
Of course, this means that we will need to improve the integration with the new deferred at some point.

Cheers,

**Comment by ardumont** [comment]
Closing as i don't think that's an issue any longer.
Feel free to reopen with more information ;)
