### ISSUE TITLE
require complete date in yyyy-mm-dd-xxx.html

### ISSUE THREAD

**Issue by sunznx** [ardumont/org2jekyll#46]
in the generated html, the format of the DATE is like this
`date: 2016-11-21`
but `date: 2016-11-21 21:20:48` would be better

**Comment by ardumont** [comment]
Right, i see where it's limited at. Will fix.

Though, i won't have the second details.

org-date are defined as for example `2015-12-23 Sat 14:20`, which means i can have as output: `2015-12-23 14:20:00` which is way better already ;)

I think it will be fine alright.

Cheers,
