### ISSUE TITLE
Allow to add front matter key/values from org

### ISSUE THREAD

**Issue by mzimmerm** [ardumont/org2jekyll#47]
I use a "clean theme" https://github.com/scotte/jekyll-clean which allows to add comments, if the post specifies a front matter key/value

> comments: true

It is simple to just add 

> #+COMMENTS: true

on top of every post, but it would be cool if there was a way to customize, or somehow persistently change the list of prompts during *org2jekyll-create-draft* to include other key/values. I apologize if I missed this is actually possible.

Thanks
Milan

**Comment by ardumont** [comment]
Now, you can define the following in your emacs configuration:

```
(custom-set-variables
  '(org2jekyll-default-template-entries-extra '(("comments" "true")))
```

Closing as i don't really expect feedback after so much time opened.

Cheers,
