### ISSUE TITLE
Dealing with images

### ISSUE THREAD

**Issue by pseudomyne** [ardumont/org2jekyll#50]
hi,
I'm toying around with **jekyll / org2jekyll** but I’ve not been able to publish images easily from orgmode. The only way I managed to publish images is by placing all of them in top level directory of jekyll and put relative paths in orgmode like this :
`[[../../../../../images/test_r.png]]` 
I strongly guess I’ve missed something somewhere (doing like this I can't see the images from orgmode, which is annoying). Would you mind explaining the correct way to deal with images in terms of paths ? Thanks.

**Comment by ardumont** [comment]
Added a demo sample [1]

Closing this now.

[1] https://github.com/ardumont/org2jekyll/blob/master/testing-blog/org/blogging-with-org2jekyll.org#6-display-image
