### ISSUE TITLE
wrong-type-argument stringp nil

### ISSUE THREAD

**Issue by louiszgm** [ardumont/org2jekyll#52]
I already set up the config through customize-group.

```
`'(org2jekyll-blog-author "louiszgm"  (org2jekyll))

 '(org2jekyll-jekyll-directory "~/louiszgm.github.io/" (org2jekyll))

 '(org2jekyll-jekyll-drafts-dir "" (org2jekyll))

 '(org2jekyll-jekyll-posts-dir "_posts/" (org2jekyll))

 '(org2jekyll-source-directory "~/orgResource/" (org2jekyll))`
```

When i use **org2jekyll-publish-posts** function , I got the error `deferred error: (wrong-type-argument stringp nil)`

but it's ok to use **org2jekyll-create-draft** function.

This is the debug backtrace
```
Debugger entered--entering a function:
* org2jekyll-publish-posts()
  funcall-interactively(org2jekyll-publish-posts)
  call-interactively(org2jekyll-publish-posts record nil)
  command-execute(org2jekyll-publish-posts record)
  #[257 "\304\305!\203\f�\306\307!!\210\307!\211\310\307!\311\")\207" [current-prefix-arg prefix-arg this-command real-this-command featurep smex smex-rank intern command-execute record] 4 "\n\n(fn CMD)"]("org2jekyll-publish-posts")
  ivy-call()
  ivy-read("M-x " ("debug-on-entry" "org-html-export-as-html" "package-install" "org2jekyll-list-posts" "toggle-debug-on-error" "debug" "customize-group" "org2jekyll-create-draft" "org2jekyll-mode" "cua-cut-region" "replace-string" "org-cut-subtree" "org2jekyll-publish" "package-refresh-contents" "kill-ring-save" "clipboard-kill-ring-save" "org2jekyll-init-current-buffer" "cd" "ri" "5x5" "arp" "dbx" "dig" "erc" "ert" "eww" "ftp" "gdb" "irc" "jdb" "man" "mpc" "pdb" "pwd" "rsh" "sdb" "vlf" "xdb" "calc" "dark" "diff" "dirs" "ffap" "gnus" "grep" "help" "ielm" "info" "life" "mail" ...) :predicate nil :require-match t :history counsel-M-x-history :action #[257 "\304\305!\203\f�\306\307!!\210\307!\211\310\307!\311\")\207" [current-prefix-arg prefix-arg this-command real-this-command featurep smex smex-rank intern command-execute record] 4 "\n\n(fn CMD)"] :sort nil :keymap (keymap (67108908 . counsel--info-lookup-symbol) (67108910 . counsel-find-symbol)) :initial-input nil :caller counsel-M-x)
  counsel-M-x()
  funcall-interactively(counsel-M-x)
  call-interactively(counsel-M-x nil nil)
  command-execute(counsel-M-x)
```

**Comment by ardumont** [comment]
Your sample configuration looks wrong.

Checking the setup sample mentioned

**Comment by ardumont** [comment]
Wrong manipulation.

> Checking the setup sample mentioned...

Checking the [setup sample](https://github.com/ardumont/org2jekyll#setup) mentioned, there is a divergence.
Can you please try adapting the configuration according to the sample and check again.

Cheers,

**Comment by louiszgm** [comment]
Thank you! @ardumont 
By the way, When i change the layout to **single**,it cannot publish the post.
How can i publish the custom layout? The **single-layout** it's my theme layout.

**Comment by ardumont** [comment]
If this issue is done, we could close it.

> By the way, When i change the layout to single,it cannot publish the post.
> How can i publish the custom layout? The single-layout it's my theme layout.

I don't understand what you mean.
I have the feeling that to answer this, i should have a pick at your configuration snippet.
Do you have a sample of this?

Also, it would be better to open another issue as we are mixing things.
That will render readability difficult for others which could have the same problem you had.

Cheers,
