### ISSUE TITLE
How to change layout value in yaml header  ?

### ISSUE THREAD

**Issue by louiszgm** [ardumont/org2jekyll#53]
When i use `M-x org2jekyll-publish-posts`, it generated the yaml header like this:

```
---
date: 2018-03-07
tags: 
- CC
author: louiszgm
layout: post
title: CC
excerpt: CC
categories: 
- CC
--- 
```

I want the `layout value to be single`, the expected yaml header i want like this:
```
date: 2018-03-07
tags: 
- CC
author: louiszgm
layout: single
title: CC
excerpt: CC
categories: 
- CC
--- 
```

Shoud i hook the plugin?

**Comment by ardumont** [comment]
I know the doc says not to do it (don't remember why though) but have you tried to:

```
#+LAYOUT: single
```

Note: I assume that the your [org2jekyll/org-publish configuration](https://github.com/ardumont/org2jekyll#setup) in the `org-publish-project-alist` custom has an entry 'single' somewhere.

> Shoud i hook the plugin?

I just don't know yet ;)
Cheers,

**Comment by louiszgm** [comment]
I have tried both way that you suggest, but it can't work. @ardumont

**Comment by ardumont** [comment]
The layouts seem to be hard-coded in some places, [1] for example.

So to allow this layout override, i think the most sensible thing to do is to
actually defines one new org2jekyll custom.

That would default to the current hard-coded values.

[1] https://github.com/ardumont/org2jekyll/blob/master/org2jekyll.el#L208
