### ISSUE TITLE
Can't install via Marmalade?

### ISSUE THREAD

**Issue by Vafa-Andalibi** [ardumont/org2jekyll#54]
Hi, 

I have added Marmalade to my emacs and it's working fine (marmalade demo installed and worked just fine) yet I don't have org2jekyll on my package list. Any idea why is that happening?  

Thanks,

**Comment by ardumont** [comment]
Hello,

> I have added Marmalade to my emacs and it's working fine (marmalade demo installed and worked just fine) yet I don't have org2jekyll on my package list. Any idea why is that happening?

No idea.

Have you tried <kbd>M-x package-refresh-contents RET</kbd> to update the package list?

Or as entertained by [marmalade's page for org2jekyll](https://marmalade-repo.org/packages/org2jekyll), directly,<kbd>M-x package-install RET org2jekyll RET</kbd>?

Cheers,

**Comment by ardumont** [comment]
You might want to try to use melpa now.

Cheers,
